/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package pandora.domain.avro;  
@SuppressWarnings("all")
public enum PandoraEnum { 
  FIRST, SECOND, THIRD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PandoraEnum\",\"namespace\":\"pandora.domain.avro\",\"symbols\":[\"FIRST\",\"SECOND\",\"THIRD\"]}");
}
